name: build-apk

on:
  workflow_dispatch:        # 수동 실행 버튼
  push:
    branches: [ main ]      # main에 푸시될 때 자동 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build with Buildozer (Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: -v ${{ github.workspace }}:/home/user/app -w /home/user/app
          run: |
            buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4   # ← v4로 변경!
        with:
          name: apk
          path: bin/*.apk
          if-no-files-found: error
